### PR TITLE
Fix mute role returning when rejoining server

### LINKED ISSUE #117: Roles are returned upon a rejoin even if the member is role-muted
### Description

In the code that returns roles when a member rejoins (GuildMemberJoinedResponder), there is no check to skip returning roles if the member is role-muted.

### Reproduction Steps

1. Mute a member
2. Ask that member to rejoin
3. Their roles will be returned and the mute role will be gone

### Expected behavior

Only the mute role will be returned

### Actual behavior

All roles will be returned

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mctaylors**
Closes #117

### CODE REVIEW

File: src/Responders/GuildMemberJoinedResponder.cs [hunk 1]
```diff
@@ -83,4 +81,30 @@ public async Task<Result> RespondAsync(IGuildMemberAdd gatewayEvent, Cancellatio
...
+        JsonNode cfg, MemberData memberData, IGuildMemberAdd gatewayEvent, IUser user, CancellationToken ct)
+    {
+        if (!GuildSettings.ReturnRolesOnRejoin.Get(cfg))
+        {
+            return Result.FromSuccess();
+        }
+
+        var assignRoles = new List<Snowflake>();
+
+        if (!GuildSettings.RemoveRolesOnMute.Get(cfg) || memberData.MutedUntil is null)
```
Comment (Octol1ttle) [inline src/Responders/GuildMemberJoinedResponder.cs:95]: Flip `||` for better readability flow

File: src/Responders/GuildMemberJoinedResponder.cs [hunk 2]
```diff
@@ -83,4 +81,30 @@ public async Task<Result> RespondAsync(IGuildMemberAdd gatewayEvent, Cancellatio
...
+
+        if (memberData.MutedUntil is not null)
+        {
+            assignRoles.Add(GuildSettings.MuteRole.Get(cfg));
+        }
+
+        var result = await _guildApi.ModifyGuildMemberAsync(
+            gatewayEvent.GuildID, user.ID,
+            roles: assignRoles, ct: ct);
+        return !result.IsSuccess ? Result.FromError(result.Error) : Result.FromSuccess();
```
Comment (Octol1ttle) [inline src/Responders/GuildMemberJoinedResponder.cs:108]:
```suggestion
        return await _guildApi.ModifyGuildMemberAsync(
            gatewayEvent.GuildID, user.ID,
            roles: assignRoles, ct: ct);
```

File: src/Responders/GuildMemberJoinedResponder.cs [hunk 3]
```diff
@@ -83,4 +81,30 @@ public async Task<Result> RespondAsync(IGuildMemberAdd gatewayEvent, Cancellatio
             GuildSettings.PublicFeedbackChannel.Get(cfg), embeds: new[] { built },
             allowedMentions: Boyfriend.NoMentions, ct: ct);
     }
+
+    private async Task<Result> ReturnRolesOnRejoinAsync(
+        JsonNode cfg, MemberData memberData, IGuildMemberAdd gatewayEvent, IUser user, CancellationToken ct)
```
Comment (Octol1ttle) [inline src/Responders/GuildMemberJoinedResponder.cs:86]: Pass IDs instead of full objects

**Review by Octol1ttle — CHANGES_REQUESTED** [review]

File: src/Responders/GuildMemberJoinedResponder.cs [hunk 4]
```diff
@@ -83,4 +80,29 @@ public async Task<Result> RespondAsync(IGuildMemberAdd gatewayEvent, Cancellatio
             GuildSettings.PublicFeedbackChannel.Get(cfg), embeds: new[] { built },
             allowedMentions: Boyfriend.NoMentions, ct: ct);
     }
+
+    private async Task<Result> ReturnRolesOnRejoinAsync(
```
Comment (Octol1ttle) [inline src/Responders/GuildMemberJoinedResponder.cs:84]: maybe `TryReturnRolesAsync` would be better? returnal is not guaranteed and "on rejoin" is pretty obvious here

File: src/Responders/GuildMemberJoinedResponder.cs [hunk 5]
```diff
@@ -83,4 +80,29 @@ public async Task<Result> RespondAsync(IGuildMemberAdd gatewayEvent, Cancellatio
...
+        JsonNode cfg, MemberData memberData, IGuildMemberAdd gatewayEvent, Snowflake userId, CancellationToken ct)
```
Comment (Octol1ttle) [inline src/Responders/GuildMemberJoinedResponder.cs:85]: ID comment applies to guild IDs too (or any IDs, for that matter)

**Review by Octol1ttle — APPROVED** [review]
